---
apiVersion: v1
kind: Namespace
metadata:
  name: security-plane
  labels:
    plan: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-plane
  labels:
    plan: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-plane
  labels:
    plan: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-plane
  labels:
    plan: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery-plane
  labels:
    plan: delivery
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-plane
  labels:
    plan: data